[package]
name = "radcam-manager"
version = "0.1.0"
edition = "2021"
license = "MIT"
default-run = "radcam-manager"

[dependencies]
radcam_manager = { path="../libs/radcam_manager" }
radcam_commands = { path="../libs/radcam_commands" }
mcm_client = { path="../libs/mcm_client" }
web_client = { path="../libs/web_client" }

anyhow = "1.0.95"
chrono = "0.4.39"
clap = { version = "4.5.26", features = ["derive"] }
once_cell = "1.20.2"
shellexpand = "3.1.0"
tokio = { version = "1.43.0", features = ["full"] }
tracing = { version = "0.1.41", features = ["log", "async-await"] }

[build-dependencies]
vergen-gix = { version = "1.0.6", default-features = false, features = ["build", "cargo"] }